### ISSUE TITLE
Can you add an example for a ForkJoinPool?

### ISSUE THREAD

**Issue by tonyfalabella** [amithkumarg/springboot-otel-micrometer-jaeger#1]
Can you add an example for a ForkJoinPool?  What you have so far is tremendously helpful - it's more info than I've found anywhere else on the web including the Micrometer /Spring Boot 3.1 migration guide.  I've yet to find an example for a ForkJoinPool.  

My initial attempt looks something like this (using `io.micrometer:context-propagation:1.0.3` ):
```
public class MicrometerWrappedForkJoinWorkerThreadFactory implements ForkJoinWorkerThreadFactory {

  @Override
  public ForkJoinWorkerThread newThread(final ForkJoinPool pool) {
    final ContextRegistry registry = ContextRegistry.getInstance();
    // Register thread local accessors (you can use SPI too)
    registry.registerThreadLocalAccessor(new ObservationThreadLocalAccessor());

    // When you set a thread local value...
    // ObservationThreadLocalHolder.setValue("hello");
    // ... we can capture it using ContextSnapshot
    final ContextSnapshot snapshot =
        ContextSnapshotFactory.builder().contextRegistry(registry).build().captureAll();

    final MicrometerWrappedForkJoinWorkerThread micrometerWrappedForkJoinWorkerThread =
        new MicrometerWrappedForkJoinWorkerThread(pool);

    snapshot.wrap(micrometerWrappedForkJoinWorkerThread);
    return micrometerWrappedForkJoinWorkerThread;
  }

  public class MicrometerWrappedForkJoinWorkerThread extends ForkJoinWorkerThread {
    /**
     * Creates a ForkJoinWorkerThread operating in the given pool.
     *
     * @param pool the pool this thread works in
     * @throws NullPointerException if pool is null
     */
    protected MicrometerWrappedForkJoinWorkerThread(final ForkJoinPool pool) {
      super(pool);
    }
  }
}
```

**Comment by amithkumarg** [comment]
@tonyfalabella If you can share a minimum viable working dummy project with your way of preferred setup of ThreadFactory and ForkJoinPool, I can help you work that out to enable micrometer tracing in there with the ideal configuration. Just taking a quick glance at your code, I can tell why this is not working for you.
```
snapshot.wrap(micrometerWrappedForkJoinWorkerThread);
return micrometerWrappedForkJoinWorkerThread;
```
here though you are wrapping the thread under context tracing but you are still returning the original object, so you lost the wrapper there.

**Comment by amithkumarg** [comment]
Added an example for ForkJoinPool Distributed Tracing.
commit: https://github.com/amithkumarg/springboot-otel-micrometer-jaeger/commit/28026167dabe5a1df79d441c0055701423f6d716

For more information & understanding, please consider checking this blog:
https://amithkumarg.medium.com/distributed-tracing-spring-boot-micrometer-and-forkjoinpool-3dc8f06885f5

**Comment by tonyfalabella** [comment]
Thanks for the update to your project and the blog post.  This worked for me.  Appreciate it Amith.
